@RefuelAPI_HostAddress = http://localhost:5094

###Create

POST {{RefuelAPI_HostAddress}}/api/v1/Vehicles/
Content-Type: application/json

{
  "Brand": "Alfa Romeo",
  "Model": "Giulia",
  "Owner": "Ale4",
  "FuelIds": ["be8f3a6e-0bd1-4dab-9bb3-0828ce6c4a7b"],
  "NickName": "Test targa",
  "licencesPlate": "AA 000 BB"
}


### Get All
GET {{RefuelAPI_HostAddress}}/api/v1/Vehicles
Accept: application/json


### Get by id 

GET {{RefuelAPI_HostAddress}}/api/v1/Vehicles/157ac01f-a604-4549-8972-bb3f6a09fd62
Accept: application/json



### Get refuels 

GET {{RefuelAPI_HostAddress}}/api/v1/Vehicles/9877dee6-a583-45d5-bbd5-1653410f633a/refuels
Accept: application/json


