@RefuelAPI_HostAddress = http://localhost:5094

###Create

POST {{RefuelAPI_HostAddress}}/api/v1/Fuels/
Content-Type: application/json

{
  "Name": "Diesel"
}

###Update

PUT {{RefuelAPI_HostAddress}}/api/v1/Fuels/4b78f14a-2a9b-46fa-9936-0d150617657d
Content-Type: application/json

{
  "Name": "GPL"
}


### GetAll
GET {{RefuelAPI_HostAddress}}/api/v1/Fuels/
Accept: application/json
Authorization: Bearer CfDJ8DmzRnrq-spNsQoW4lqmqvs4eXFwUd8-TEm4tGJhZObl2lmKc2is1gpwjpFKkyauSMp7tXOczLQHfiAtFkNdguJlV2kZNWdojIpwLlxCv4s-wSZPl4IKDAT1HHln8zPgbGiZS594NtkX8A83EphJXxSrmcYsQq7LYrfOABRirWdw8KlOaTcN5HsHou99KDOXBCni6qCkNe3_xquzj31bDMqah4XjZoPLX7tPj-LAluOCfJvZqIXDcmAe9jJNkIp64KkqtDjq-g2mj21AGbkFf0lv_ypRkTsPgd9cR8jhYBUfU44gYBq-LDGWv9h84QGy9FDjSn1mHDFqdAAb_U0VLf__hMr8ReEC52PJvgmpJWT3tPcNkNXfHD4yLZZNDW6E6zu_YQAFMM6BbDWV_pG964LOjxvy-l-3KbOrz59TD1Pw-VK8Rri0kgr2kFHQPeF0yGZP8bSPbmaX8Pls3MWyzmojAj41iWpox-dN3HGEpyZSWBd5un3LBIbJobnRH4D6uJUEQAT-MzwEXzXy9_BwFMYSolxdYFz5esy1WjhzTOrMK2laVc03UAzo82dBfvZiGKCR7PZUnS_KjtmxCVc55ta-3sSzo29JWkqeb5z-ZUSYov40bR2H0DI6WTd7fw0hPTUHvNvWfyt0DOjN41mcmkMmP4osbDiknMJVwIu6sAztPNVUHsDWRLCTxJMY5vMLFL1yTT6TGR7xQVcr7hKckNizvZMiONVcLkSLWEx67qx3NLVcvriZWPr6oc87nQpGEeDVqRQexFD1X4Najlu_VErYco0FrZOLhLMvNHvDgnmL

### Get One

GET {{RefuelAPI_HostAddress}}/api/v1/Fuels/3a701524-4f1c-4b7f-b2a7-82bc95b6e381
Accept: application/json

### Delete one

DELETE {{RefuelAPI_HostAddress}}/api/v1/Fuels/c1254ecb-d754-472d-8513-deb7250489ca
Accept: application/json