// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Refuel.Persistence;

#nullable disable

namespace Refuel.Persistence.Migrations
{
    [DbContext(typeof(RefuelDbContext))]
    partial class RefuelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Refuel.Domain.Entities.Fuel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("fuels", (string)null);
                });

            modelBuilder.Entity("Refuel.Domain.Entities.GasStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("gas_stations", (string)null);
                });

            modelBuilder.Entity("Refuel.Domain.Entities.Refuel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<Guid>("FuelId")
                        .HasColumnType("TEXT")
                        .HasColumnName("fuel_id");

                    b.Property<Guid>("GasStationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("gas_station_id");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<float>("OdometerKm")
                        .HasColumnType("REAL")
                        .HasColumnName("odometer_km");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL")
                        .HasColumnName("quantity");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("REAL")
                        .HasColumnName("total_price");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("FuelId");

                    b.HasIndex("GasStationId");

                    b.HasIndex("VehicleId");

                    b.ToTable("refuels", (string)null);
                });

            modelBuilder.Entity("Refuel.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("brand");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("model");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner");

                    b.HasKey("Id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("gas_station_fuels", b =>
                {
                    b.Property<Guid>("fuel_id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("gas_station_id")
                        .HasColumnType("TEXT");

                    b.HasKey("fuel_id", "gas_station_id");

                    b.HasIndex("gas_station_id");

                    b.ToTable("gas_station_fuels");
                });

            modelBuilder.Entity("vehicle_fuels", b =>
                {
                    b.Property<Guid>("fuel_id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("vehicle_id")
                        .HasColumnType("TEXT");

                    b.HasKey("fuel_id", "vehicle_id");

                    b.HasIndex("vehicle_id");

                    b.ToTable("vehicle_fuels");
                });

            modelBuilder.Entity("Refuel.Domain.Entities.Refuel", b =>
                {
                    b.HasOne("Refuel.Domain.Entities.Fuel", "Fuel")
                        .WithMany()
                        .HasForeignKey("FuelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Refuel.Domain.Entities.GasStation", "GasStation")
                        .WithMany()
                        .HasForeignKey("GasStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Refuel.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fuel");

                    b.Navigation("GasStation");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("gas_station_fuels", b =>
                {
                    b.HasOne("Refuel.Domain.Entities.Fuel", null)
                        .WithMany()
                        .HasForeignKey("fuel_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Refuel.Domain.Entities.GasStation", null)
                        .WithMany()
                        .HasForeignKey("gas_station_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("vehicle_fuels", b =>
                {
                    b.HasOne("Refuel.Domain.Entities.Fuel", null)
                        .WithMany()
                        .HasForeignKey("fuel_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Refuel.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("vehicle_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
